version: '3.8'

services:
  ravenchain:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # For REST API
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    command: python main.py
    restart: unless-stopped

  # Uncomment when implementing REST API
  # api:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - ENVIRONMENT=development
  #     - DEBUG=1
  #   command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
  #   depends_on:
  #     - ravenchain

  # Uncomment when adding database
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=ravenchain
  #     - POSTGRES_PASSWORD=ravenchain
  #     - POSTGRES_DB=ravenchain
  #   ports:
  #     - "5432:5432"

# Uncomment when adding database
# volumes:
#   postgres_data:
