name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ravenchain_test
          POSTGRES_USER: ravenchain
          POSTGRES_PASSWORD: ravenchain
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev python3-dev gcc
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        pip install pytest pytest-cov coverage psycopg2-binary
    
    - name: Run tests with coverage
      env:
        RAVENCHAIN_DB_HOST: localhost
        RAVENCHAIN_DB_PORT: 5432
        RAVENCHAIN_DB_NAME: ravenchain_test
        RAVENCHAIN_DB_USER: ravenchain
        RAVENCHAIN_DB_PASS: ravenchain
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest --cov=ravenchain --cov-report=xml --cov-report=term-missing tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true
